### ISSUE TITLE
400 is returned for all requests that don't pass validation

### ISSUE THREAD

**Issue by switzersc** [spilio/openreferral-validator#1]
Right now the validator API returns a `400 Bad Request` whenever a request is made with a file that doesn't meet validation requirements. This was pretty confusing because 400s are meant to be returned for [malformed syntax](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html), not semantic issues or otherwise syntactically valid requests. This error code led me to believe there was something malformed about my file or HTTP request, and it took about an hour of debugging and head-scratching for us to realize that the request and the CSV themselves were well-formed but that our CSV just didn't pass the validation logic. 

Notably, when using `curl` you probably won't see the 400 status code response unless you're using the `verbose` flag, and you will see the validation message; however, when using Postman or in our case Ruby HTTP clients, only the error is surfaced, not the validation message in the body. 

I'd advocate for updating the validation API to return a different error status code (e.g. 422 - semantically bad request), or to return a 200 with the validation message in the body. I'm suggesting a 200 because the API request itself is actually valid: the endpoint is performing the function we expect, which is checking the received entity against some logic, and the response includes information that we've asked for (the validation message). Therefore as a client, everything is OK, I've just now gotten info that I have work to do. 

Thoughts?

**Comment by switzersc** [comment]
Also, totally happy to make a pull request but wanted to discuss first. If you don't agree with changing status codes,  I can make a PR to update the readme to include info on error messaging. =]

**Comment by xrysanthos** [comment]
Hey @switzersc, sorry for not replying earlier - I think I've missed the ticket notification for some reason.  Thank you very much for your feedback!  Actually you are right - the top level 400 status code refers to a bad structured request.  I agree that the **422** code seems to be the most appropriate for this case.  

I suggest that we stick with the error status in this case - but with a more suitable code - as it must be obvious to the client that something was wrong.  Since the need behind this microservice is to apply certain validation rules on a set of data - both on a structural / schema and relationship / integrity levels - clients are expected to anticipate a blocking behavior.  For example, in a future scenario someone might want to create a data workflow pipeline (ETL, etc) and use the validator as a block - in this case if the validation stage should act as a filter and either block or let the flow pass through.  As you can imagine it would need extra logic at the orchestration level in order to check 200 responses with potential errors within.

Having said that, I will change the error code to 422 and update the docs.  Thanks again for pointing this out!
